# Generated by Django 5.2.17 on 2026-09-08 12:48

import django.utils.timezone
import monitor.models.upstream_pricing
from django.db import migrations, models
from copy import deepcopy
from hashlib import sha256
import json


LEGACY_FIELDS = (
    "fast_correction_enabled", "fast_correction_rules",
    "long_context_correction_enabled", "long_context_correction_rules",
    "model_correction_enabled", "model_correction_rules",
)
RETIRED_PRICING_ANNOUNCEMENTS = (
    "sub2api-wallet-conversion-2026-09-08",
    "sub2api-long-context-correction-2026-09",
    "sub2api-gpt6-model-correction-2026-09",
    "sub2api-fast-model-correction-0-1-179",
)


def freeze_historical_pricing(apps, schema_editor):
    """Freeze local history only. Network writes belong to runmonitor."""
    alias = schema_editor.connection.alias
    settings_model = apps.get_model("monitor", "AppSettings")
    observation_model = apps.get_model("monitor", "Observation")
    config = settings_model.objects.using(alias).filter(pk=1).first()
    has_history = observation_model.objects.using(alias).filter(account_id__gt=0).exists()
    has_history = has_history or apps.get_model(
        "monitor", "APIUsageRequestFact"
    ).objects.using(alias).exists()
    historical_config = config or settings_model(pk=1)
    frozen = {name: deepcopy(getattr(historical_config, name)) for name in LEGACY_FIELDS}
    policy = {
        "fast_rules": [
            {"model_pattern": row["model_pattern"], "multiplier": row["target_multiplier"]}
            for row in frozen["fast_correction_rules"]
        ] if frozen["fast_correction_enabled"] else [],
        "model_rules": deepcopy(frozen["model_correction_rules"])
        if frozen["model_correction_enabled"] else [],
        "long_context_pricing_enabled": None,
    }
    migration_error = ""
    long_rules = frozen["long_context_correction_rules"]
    if frozen["long_context_correction_enabled"] and long_rules:
        if all(str(row["target_multiplier"]) == "1" for row in long_rules):
            policy["long_context_pricing_enabled"] = False
        elif not all(
            row["target_multiplier"] == row["source_multiplier"] for row in long_rules
        ):
            migration_error = (
                "旧长上下文规则不能等价转换为 Sub2API 分组统一开关；"
                "尚未写入上游，请在上游计费设置中选择新策略后手动应用。"
            )
    cutoff = django.utils.timezone.now()
    apps.get_model("monitor", "UpstreamPricingState").objects.using(alias).create(
        pk=1,
        policy=policy,
        legacy_policy=frozen if config is not None or has_history else {},
        local_cutoff_at=cutoff,
        status="failed" if migration_error else "pending",
        attempted_at=cutoff if migration_error else None,
        last_error=migration_error,
    )
    old_digest = sha256(json.dumps(
        {**frozen, "calculation_version": "fast-long-model-v1"},
        ensure_ascii=False, sort_keys=True, separators=(",", ":"),
    ).encode()).hexdigest()
    frozen_digest = sha256(json.dumps(
        {"policy": frozen, "calculation_version": "fast-long-model-v1", "local_cutoff_at": cutoff.isoformat()},
        ensure_ascii=False, sort_keys=True, separators=(",", ":"),
    ).encode()).hexdigest()
    apps.get_model("monitor", "ParticipantAPIUsageSnapshot").objects.using(alias).filter(
        fast_correction_rules_hash=old_digest,
        fast_correction_enabled=frozen["fast_correction_enabled"],
    ).update(fast_correction_rules_hash=frozen_digest)
    observation_model.objects.using(alias).filter(account_id__gt=0).update(
        correction_source="local",
        frozen_correction_policy=frozen,
        pricing_epoch="local",
    )
    observation_model.objects.using(alias).filter(account_id__lt=0).update(
        correction_source="none", pricing_epoch="cpa"
    )
    apps.get_model("monitor", "MonitoredAccount").objects.using(alias).filter(
        provider="cpa"
    ).update(pricing_epoch="cpa")
    apps.get_model("monitor", "AnnouncementRead").objects.using(alias).filter(
        announcement_code__in=RETIRED_PRICING_ANNOUNCEMENTS
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0053_auto_apply_recommendations_default_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamPricingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.JSONField(default=monitor.models.upstream_pricing.default_upstream_pricing_policy)),
                ('legacy_policy', models.JSONField(default=dict)),
                ('local_cutoff_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('targets', models.JSONField(default=list)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='pricing_epoch',
            field=models.CharField(default='upstream-v1:pending', max_length=80),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='upstream_pricing_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='correction_source',
            field=models.CharField(choices=[('local', '历史本地修正'), ('upstream', '上游已修正'), ('none', '未修正')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='observation',
            name='frozen_correction_policy',
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='pricing_epoch',
            field=models.CharField(default='upstream-v1:pending', max_length=80),
        ),
        migrations.RunPython(freeze_historical_pricing, migrations.RunPython.noop),
    ]
