# Generated by Django 5.2.17 on 2026-09-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0056_quotapool_cpa_billing_anchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpausageevent',
            name='reasoning_effort',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
