# Generated by Django 5.2.17 on 2026-09-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0056_pricing_announcement_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBurstSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('participant_users', models.JSONField(default=dict)),
                ('base_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryBurstCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resets_at', models.DateTimeField()),
                ('quota_model', models.CharField(max_length=32)),
                ('members', models.JSONField(default=list)),
                ('is_burst_cycle', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement', models.JSONField(default=list)),
                ('evidence_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='burst_cycles', to='monitor.monitoredaccount')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='monitor.temporaryburstsession')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'settled_at'], name='burst_pending_cycles')],
                'constraints': [models.UniqueConstraint(fields=('account', 'resets_at'), name='unique_burst_account_cycle')],
            },
        ),
    ]
