# Generated by Django 5.2.17 on 2026-09-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0057_gpt6_fast_default'),
        ('monitor', '0057_temporary_burst'),
    ]

    operations = [
    ]
