# Generated by Django 5.2.17 on 2026-09-14 07:13

import monitor.models.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0057_cpa_usage_reasoning_effort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monitoredaccount',
            name='account_provider_identity_valid',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gpt_load_auth_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gpt_load_base_url',
            field=models.CharField(default='http://host.docker.internal:3001', max_length=500, validators=[monitor.models.validators.validate_service_url]),
        ),
        migrations.AddField(
            model_name='cpaapikey',
            name='external_key_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpaapikey',
            name='source',
            field=models.CharField(choices=[('cpa', 'CPA'), ('gpt_load', 'GPT-Load')], db_index=True, default='cpa', max_length=16),
        ),
        migrations.AddField(
            model_name='cpausageevent',
            name='cost_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cpausageevent',
            name='pricing_completeness',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cpausageevent',
            name='source',
            field=models.CharField(choices=[('cpa', 'CPA'), ('gpt_load', 'GPT-Load')], db_index=True, default='cpa', max_length=16),
        ),
        migrations.AddField(
            model_name='cpausageevent',
            name='source_cost_nano_usd',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpausageevent',
            name='usage_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='gpt_load_credential_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='gpt_load_cutover_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='gpt_load_group_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='gpt_load_logs_synced_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredaccount',
            name='provider',
            field=models.CharField(choices=[('sub2api', 'Sub2API'), ('cpa', 'CPA'), ('gpt_load', 'GPT-Load')], default='sub2api', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='cpaapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key_id__isnull', False)), fields=('source', 'external_key_id'), name='unique_gateway_external_key'),
        ),
        migrations.AddConstraint(
            model_name='monitoredaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cpa_auth_index__isnull', True), ('external_account_id__isnull', False), ('gpt_load_credential_id__isnull', True), ('gpt_load_cutover_at__isnull', True), ('gpt_load_group_id__isnull', True), ('provider', 'sub2api')), models.Q(('cpa_auth_index__isnull', False), ('external_account_id__isnull', True), ('gpt_load_credential_id__isnull', True), ('gpt_load_cutover_at__isnull', True), ('gpt_load_group_id__isnull', True), ('provider', 'cpa')), models.Q(('external_account_id__isnull', True), ('gpt_load_credential_id__isnull', False), ('gpt_load_cutover_at__isnull', False), ('gpt_load_group_id__isnull', False), ('provider', 'gpt_load')), _connector='OR'), name='account_provider_identity_valid'),
        ),
    ]
