# Generated by Django 5.2.17 on 2026-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0058_merge_0057_gpt6_fast_default_0057_temporary_burst'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryburstcycle',
            name='settlement_context',
            field=models.JSONField(default=dict),
        ),
    ]
