# Generated by Django 5.2.17 on 2026-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0059_burst_settlement_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryburstsession',
            name='exhaustion_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('limit_exhausted', '额度耗尽'), ('recommendation_changed', '建议变化'), ('rate_changed', '汇率变化'), ('collection_error', '采集失败'), ('temporary_burst_exhaustion', '爽蹬用满提醒'), ('test', '测试')], max_length=32),
        ),
    ]
