# Generated by Django 5.2.17 on 2026-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0060_burst_exhaustion_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryburstcycle',
            name='carry_edits',
            field=models.JSONField(default=list),
        ),
    ]
