# Generated by Django 5.2.17 on 2026-09-12 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0063_burst_same_cycle_restart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTemporaryDisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('account', '整个账号'), ('model', '单个模型')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('restore_context', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restore_at', models.DateTimeField()),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restore_source', models.CharField(blank=True, max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_disables', to='monitor.monitoredaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_disables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '临时禁用',
                'verbose_name_plural': '临时禁用',
                'ordering': ['started_at', 'id'],
                'indexes': [models.Index(fields=['restored_at', 'restore_at'], name='temporary_disable_due')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('restored_at__isnull', True)), fields=('account', 'scope'), name='unique_active_account_temporary_disable'), models.CheckConstraint(condition=models.Q(models.Q(('model', ''), ('scope', 'account')), models.Q(('model__gt', ''), ('scope', 'model')), _connector='OR'), name='temporary_disable_model_matches_scope')],
            },
        ),
    ]
